import "./globals.css";
import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import NavBar from "./NavBar";
import AuthProvider from "./auth/Provider";
// import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500"] });
// const myOwnFont = localFont({
//   src: "@/public/fonts/nameOfMyFont",
//   variable: "--font--NAME";
// To override classname generated by Next. Need to register it in tailwind.config.ts
// });

export const metadata: Metadata = {
  title: "My application",
  description: "Generated by create next app",
  // For social media platforms sharing
  openGraph: {
    title: "...",
    description: "...",
    // ...
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme="retro" lang="en">
      <body className={roboto.className}>
        {/* <body className={myOwnFont.variable}> */}
        <AuthProvider>
          <NavBar />
          <main className="p-5">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
